name: ci

on:
  push:
    branches: [ dev ]
  pull_request_review:
    types:
      - opened
      - edited
  pull_request:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: corepack use pnpm@latest

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --coverage=false

      - name: Build
        run: npm run build
